### ISSUE TITLE
Add a plugin in a pre-compiled binaries Sofa

### ISSUE THREAD

**Issue by Dong-Le-gnoD** [SofaDefrost/SofaViscoElastic#18]
Hi,
This is not a issue, I am here to seek an answer. 
I am using a pre-compiled binaries 23.06 Sofa. Even though there are several available plugins, I need the plugin SofaViscoElastic. How do I add the plugin and build the Sofa?
Thank you!

**Comment by pasqualeferr94** [comment]
Hello,
Yes, sorry. I didn't generate a pre-compiled version of the plugin because I needed to add some things to make it more complete. You must have the source code version of SOFA if you need it. You can follow the instructions on installing SOFA for your OS on the website. Hence, then you can add the SofaViscoElastic folder in the "src/applications/plugins" and add its name to the CMakeList.txt of the same folder (remember to install first the SofaPython3 plugin because it has a dependency on that one).
